name: Build for Web

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.51

    - name: Compile
      run: |
        mkdir build_web
        
        emcc *.cpp -O2 \
        -std=c++11 \
        -s USE_SDL=2 \
        -s ALLOW_MEMORY_GROWTH=1 \
        -s "EXPORTED_RUNTIME_METHODS=['ccall','cwrap']" \
        --preload-file "Stellardrone - Eternity.mp3" \
        -o build_web/index.html

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-game
        path: build_web
