name: Build for Web (Single Thread Compatible)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.51

    - name: Compile
      run: |
        mkdir build_web
        
        emcc src/*.cpp \
        -I src \
        -O3 \
        -flto \
        -std=c++11 \
        -s USE_SDL=2 \
        -s ALLOW_MEMORY_GROWTH=1 \
        -s INITIAL_MEMORY=134217728 \
        -s "EXPORTED_RUNTIME_METHODS=['ccall','cwrap']" \
        -s ASSERTIONS=0 \
        -s DISABLE_EXCEPTION_CATCHING=1 \
        -s AGGRESSIVE_VARIABLE_ELIMINATION=1 \
        --preload-file assets \
        --use-preload-plugins \
        -o build_web/index.html

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-game
        path: build_web
